### ISSUE TITLE
Issue with scoop/windows installation of 22.11.1-2

### ISSUE THREAD

**Issue by tuanpham96** [conda-forge/miniforge#421]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We have an installation job in our CI using `scoop` on Windows Server images (`mcr.microsoft.com/windows/servercore:1809`). Previously via `scoop`, the job was successful with `mambaforge@22.9.0-2`. Calling `conda` in Powershell was ok. 

However, with `22.11.1-2`, it is now not successfully installed. It was missing even `python` at first. But even after installing `python` then reinstalling `mambaforge`, `conda` is not callable.

Here are the links to the logs of:

- :x:  [`22.11.1-2`](https://gitlab.com/fleischmann-lab/calcium-imaging/calimag/-/jobs/3722946580): installed with 

  ```bash
  scoop install git 
  scoop install python # had to add this
  scoop bucket add extras
  scoop install mambaforge # no version specified # LINE 96 of log
  conda init powershell # error here
  ```

- :heavy_check_mark:  and when forcing to fall back on previous version [`22.9.0-2`](https://gitlab.com/fleischmann-lab/calcium-imaging/calimag/-/jobs/3723138431), installed with

  ```bash
  scoop install git 
  scoop install python # optional, dont really need this
  scoop bucket add extras
  scoop install mambaforge@22.9.0-2 # fallback # LINE 96 of log
  conda init powershell # ok here moving forward
  ```

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by hmaarrfk** [comment]
It is somewhat hard for us to troubleshoot scoop, a shim we don't support.

Can you help us find the  commands it runs so somebody with a windows machine can troubleshoot.

**Comment by tuanpham96** [comment]
> help us find the commands it runs so

Did you mean `scoop` as it? If so, it is installed via `powershell` with admin rights in the CI or local docker image

```shell
# in powershell
iex "& {$(irm get.scoop.sh)} -RunAsAdmin"  # maybe can remove the run as admin if run on local machine? 
scoop install git 
scoop install python 
scoop bucket add extras

# if run install without version, the conda command cannot be found 
scoop install mambaforge 
conda init powershell

# if run install WITH version, the conda command is usable
scoop install mambaforge@22.9.0-2 
conda init powershell
```

**Comment by hmaarrfk** [comment]
Sorry, i didn't phrase my question well enough.

What is the exact bat or powershell command used by scoop, to install mambaforge?

**Comment by hmaarrfk** [comment]
cc @jaimergp

**Comment by hmaarrfk** [comment]
Ah. Was it different between windows and Unix?

I tried to maintain the same defaults for Unix, but didn't test on windows.

**Comment by tuanpham96** [comment]
@hmaarrfk It should be just `scoop bucket add extras` and `scoop install mambaforge` together. Not sure about what goes on in the background. 

So I checked the the directory in which `scoop` should be installing `mambaforge` into. For earlier versions, there would be many files, as expected. But for this version, there are 2 files (`install.json` and `manifest.json`) which I assume are from `scoop`?

The directory would be `~/scoop/apps/mambaforge/<version>/`

**Comment by tuanpham96** [comment]
For both working and not-working versions, `where conda` would not return anything. 

But `get-command conda` would return the source as `C:\Users\ContainerAdministrator\scoop\apps\mambaforge\current\scripts\conda.exe` when `22.9.0-X` is installed; but it would return an error for `22.11.1-X`

**Comment by hmaarrfk** [comment]
xref: https://github.com/ScoopInstaller/Extras/issues/10420

**Comment by c-ortbauer** [comment]
I'm pretty sure the root of the failed scoop install is the check for an empty install directory.
Scoop tries to install into the same folder the installer itself is located in. This worked with the previous version but not with the new one.

I already created a PR that fixes the issue by first moving the installer to different directory. ScoopInstaller/Extras#10457

**Comment by tuanpham96** [comment]
@jaimergp Thanks for the info! I was doing it in a Windows Server docker image so the UI wouldn't be an option. I arrived at [my statement above](https://github.com/conda-forge/miniforge/issues/421#issuecomment-1421316795) about whether paths are modified by checking `$env:PATH` in powershell actually.

@c-ortbauer Thank you for creating the PR. Unfortunately it still didn't work for me. I tried to install with your modified `mambaforge.json` in a fresh Windows Server image but I still ran into the same issues as above.

**Comment by jaimergp** [comment]
> I'm pretty sure the root of the failed scoop install is the check for an empty install directory.

Hm, in `/S`ilent mode, the installer should just ignore the warning and continue. We added [this line](https://github.com/conda/constructor/blob/3ecd7048439c82099ea6da4e290886004b4f8790/constructor/nsis/main.nsi.tmpl#L786) precisely to avoid the installer hanging indefinitely for an answer, but maybe it's having a different outcome?

**Comment by tuanpham96** [comment]
Based on this [diff](https://github.com/conda-forge/miniforge/compare/22.9.0-3...22.11.1-0?diff=split#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2b) between 22.9 to 22.11, there are 3 main code changes:

- pinning `setuptools 65.*`
- upgrade to `constructor>=3.4.2"` 
- and removal of `nsis` for windows

```python
if [[ "${TARGET_PLATFORM}" == win-* ]]; then
    conda install --yes "nsis=3.01" --channel conda-forge --override-channels
fi
```

The last one seems very specific to windows, which @c-ortbauer also had issues with. Could that be the reason?

**Comment by jaimergp** [comment]
The big change is moving to constructor 3.4.x from 3.3.x. The diff is quite large:

https://github.com/conda/constructor/compare/3.3.1..3.4.2

We have been ironing this out for a long time but it's a project with many rough edges. I am not surprised if we discover that previous unintended (or unaccounted) behaviour was in use and it's now broken (but technically "fixed" in intent).

I need to spin a VM to check this, so I'll see what I can do! Thanks for the continued feedback, really appreciated!

**Comment by jaimergp** [comment]
So the scoop JSON has this block:

```json
...
    "env_add_path": [
        "scripts",
        "Library\\bin"
    ],
...
```

, which is what adds things to PATH. That mystery is solved.

I think @c-ortbauer's solution in https://github.com/ScoopInstaller/Extras/pull/10457 should fix things. If I remove the `/S` switch from the JSON I can reproduce the "directory not empty" error.

**Comment by YWtheGod** [comment]
in /Silent mode, the installer just do nothing and quit, and this cause the issue

**Comment by jaimergp** [comment]
Hm, the process is being `-Wait`ed [here](https://github.com/ScoopInstaller/Extras/blob/1a11787e60a70251592cb33a231115388872c18c/bucket/mambaforge.json#LL18C13-L18C13) and our [CI also waits](https://github.com/conda/constructor/blob/15c6150fbb6ac2ceb6bc3c43729f90704b6163e8/scripts/run_examples.py#L182) successfully ([from here](https://github.com/conda/constructor/actions/runs/4132492930/jobs/7142654548#step:13:64)):

```
miniforge
---------
coverage run --branch --append -m constructor -v D:\a\constructor\constructor\examples\miniforge --output-dir C:\Users\runneradmin\AppData\Local\Temp\tmpcyw5ltmq\miniforge-93ds2cvt --conda-exe C:\Miniconda\envs\constructor/standalone_conda/conda.exe
--- Done in 0:00:48.839204
--- Testing Miniforge3-4.10.1-0-Windows-x86_64.exe
cmd.exe /c start /wait C:\Users\runneradmin\AppData\Local\Temp\tmpcyw5ltmq\miniforge-93ds2cvt\Miniforge3-4.10.1-0-Windows-x86_64.exe /S /D=C:\Users\runneradmin\AppData\Local\Temp\tmpcyw5ltmq\miniforge-93ds2cvt\tmpomxh63g4
--- Done in 0:00:28.099688
cmd.exe /c start /wait C:\Users\runneradmin\AppData\Local\Temp\tmpcyw5ltmq\miniforge-93ds2cvt\tmpomxh63g4\Uninstall-Miniforge3.exe /S _?=C:\Users\runneradmin\AppData\Local\Temp\tmpcyw5ltmq\miniforge-93ds2cvt\tmpomxh63g4
--- Done in 0:00:04.734893
```

**Comment by vdsbenoit** [comment]
I have a similar issue **without using scoop**. It seems the `AddToPath` option is discarded. 

I run this command in a Dockefile:

```powershell
curl -fsSLo mambaforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe
Start-Process .\mambaforge.exe -Wait -ArgumentList "/S /InstallationType=AllUsers /RegisterPython=1 /AddToPath=1"
```

Everything seems to be properly installed but the PATH is no longer updated.

**Comment by jaimergp** [comment]
@vdsbenoit - that's intended and unfortunately there's no way to signal that from the silent mode. See https://github.com/conda/constructor/pull/584 for details.

**Comment by vdsbenoit** [comment]
Thank you so much for explanation @jaimergp ! I fixed my issue by passing the `/InstallationType=JustMe` to the installer.

**Comment by ReimarBauer** [comment]
@vdsbenoit May be you can help me to get mine working?
```
install-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge (1/2)
        run: |
          cd %GITHUB_WORKSPACE%
          curl -L0 https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe --output mambaforge-installer.exe;
          call mambaforge-installer.exe -Wait -ArgumentList "/S /InstallationType=JustMe /RegisterPython=1 /AddToPath=1"
```
I do see it downloading but somehow it gets not installed
'mambaforge-installer.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.

Could you may be provide a short example where I can learn from what I did wrong?

**Comment by vdsbenoit** [comment]
It looks like another issue. Are you sure `mambaforge-installer.exe` was properly downloaded ? 

Moreover, I see that you use `-Wait` and `-ArgumentList`, which are arguments of the `Start-Process` command (from PowerShell), while you use the `call` command (from cmd). Is there a reason to use cmd and call here ?

Could you try this instead ?

```
install-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge (1/2)
        run: |
          cd %GITHUB_WORKSPACE%
          curl.exe -fsSLo mambaforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe
          Start-Process .\mambaforge.exe -Wait -ArgumentList "/S /InstallationType=JustMe /RegisterPython=1 /AddToPath=1"
```

**Comment by ReimarBauer** [comment]
Found my mistake

Take care to have /S and /D at the end 

```
install-mamba-on-windows-pwsh:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge by curl(1/2)
        run: |
          curl.exe -fsSLo mambaforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe
          Start-Process .\mambaforge.exe -Wait -ArgumentList "/InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=$($env:USERPROFILE)\mambaforge"

      - name: check mamba info(2/2)
        run: |
          $env:Path += ";$($env:USERPROFILE)\mambaforge\condabin"
          mamba info

  install-mamba-on-windows-cmd:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3

      - name: Install mambaforge by curl(1/2)
        run: |
          curl.exe -fsSLo mambaforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe
          start /wait "" mambaforge.exe /InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=%UserProfile%\mambaforge
      - name: check mamba info(2/2)
        run: |
          set PATH=%PATH%;%USERPROFILE%\mambaforge\condabin
          mamba info
```
