### ISSUE TITLE
Conda env create outputs debug information (@echo on)

### ISSUE THREAD

**Issue by gammag4** [conda-forge/miniforge#691]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Conda outputs debug info even though verbosity is set to zero, as if `@echo on` was set in the script

Miniforge version: 24.9.2-0 (from [here](https://github.com/conda-forge/miniforge/releases/download/24.9.2-0/Miniforge3-Windows-x86_64.exe))

Tested with this env.yml file:

```yml
name: test
channels:
  - conda-forge
  - nvidia/label/12.4.1
dependencies:
  - python=3.12
  - cuda-toolkit=12.4.1
  - cupy
  - cudnn
  - cutensor
```

### Installed packages

```shell
python=3.12
cuda-toolkit=12.4.1
cupy
cudnn
cutensor
```

### Environment info

```shell
name: test
channels:
  - conda-forge
  - nvidia/label/12.4.1
dependencies:
  - python=3.12
  - cuda-toolkit=12.4.1
  - cupy
  - cudnn
  - cutensor
```
